/**
 * SecondBrainHandler — Slack interaction layer for Second Brain mode.
 *
 * Handles all second-brain specific Slack interactions:
 *   - DM capture: raw text → hot sled tagged "capture"
 *   - /save <url>: fetch URL content + store tagged "bookmark"
 *   - /ask <query>: vector search warm tier → reply inline, or LLM with context
 *   - 📌 (pushpin) reaction: fetch original message → store tagged "bookmark"
 *   - Thread reply to bot message: linked note with backref to parent memory id
 *
 * Storage convention:
 *   All notes are stored via bridge.remember() with at least the tags:
 *     ["second_brain", <source_tag>]
 *   where <source_tag> is one of:
 *     "capture"   — plain DM text
 *     "bookmark"  — /save URL or 📌 reaction
 *     "linked"    — thread reply linked to a parent note
 *
 * /ask query flow:
 *   bridge.recall(query, limit) → max score ≥ confidenceThreshold?
 *     yes → build inline reply from top results (no LLM)
 *     no  → bridge.escalate(prompt with retrieved context) → reply in thread
 *
 * Bell Tower events:
 *   After each capture, this handler posts a GristEvent on channel
 *   "second_brain" so that Bell Tower watches (and the Python processor)
 *   can react to new notes without polling.
 */

import type { WebClient } from "@slack/web-api";
import type { IBridge } from "../core/bridge.js";

// ── Config ─────────────────────────────────────────────────────────────────────

export interface SecondBrainConfig {
  /**
   * Minimum recall score to answer a /ask query without LLM escalation.
   * Default: 0.85
   */
  confidenceThreshold?: number;
  /**
   * Maximum number of warm-tier notes to retrieve per /ask query.
   * Default: 5
   */
  maxRecallLimit?: number;
  /**
   * Maximum characters of a single note's content to include in a Slack reply.
   * Default: 400
   */
  snippetLength?: number;
}

// ── Result types ───────────────────────────────────────────────────────────────

export interface CaptureResult {
  /** Ledger memory id of the stored note. */
  memoryId: string;
  /** Capture source tag, e.g. "capture" | "bookmark" | "linked". */
  source: string;
  /** Original Slack message timestamp, if available. */
  slackTs?: string;
}

export interface QueryResult {
  /** Text to post back to Slack. */
  replyText: string;
  /** Number of warm-tier results that were retrieved. */
  sourceCount: number;
  /** Whether the answer was generated by the LLM (true) or inline (false). */
  usedLlm: boolean;
}

// ── SecondBrainHandler ────────────────────────────────────────────────────────

export class SecondBrainHandler {
  private readonly confidenceThreshold: number;
  private readonly maxRecallLimit: number;
  private readonly snippetLength: number;

  constructor(
    private readonly bridge: IBridge,
    private readonly web: WebClient,
    config: SecondBrainConfig = {},
  ) {
    this.confidenceThreshold = config.confidenceThreshold ?? 0.85;
    this.maxRecallLimit = config.maxRecallLimit ?? 5;
    this.snippetLength = config.snippetLength ?? 400;
  }

  // ── Capture ────────────────────────────────────────────────────────────────

  /**
   * Store a plain-text note (DM or forwarded message) in the hot sled.
   *
   * Tags: ["second_brain", "capture"]
   * If parentMemoryId is provided, also adds "linked" tag and appends
   * the parent id to the content so the Python processor can build backlinks.
   */
  async captureNote(
    text: string,
    slackTs?: string,
    parentMemoryId?: string,
  ): Promise<CaptureResult> {
    const source = parentMemoryId ? "linked" : "capture";
    const tags = ["second_brain", source];
    if (slackTs) tags.push(`slack_ts:${slackTs}`);

    let content = text.trim();
    if (parentMemoryId) {
      content += `\n\n[backlink:${parentMemoryId}]`;
    }

    const memoryId = await this.bridge.remember(content, tags);

    // Emit a bus-visible event so Bell Tower watches and the Python processor
    // can react to new captures without polling.
    try {
      await this.bridge.triage({
        channel: "second_brain",
        payload: { action: "capture", memoryId, source, slackTs },
        priority: "low",
        tags: { second_brain_action: "capture", second_brain_source: source },
      });
    } catch {
      // Non-fatal — triage notification is best-effort.
    }

    return { memoryId, source, slackTs };
  }

  /**
   * Fetch a URL, strip HTML to plain text, and store as a bookmark note.
   *
   * Tags: ["second_brain", "bookmark", "url"]
   */
  async saveUrl(url: string, slackTs?: string): Promise<CaptureResult> {
    let content: string;

    try {
      content = await _fetchUrl(url);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      content = `[URL fetch failed: ${msg}]\nURL: ${url}`;
    }

    const tags = ["second_brain", "bookmark", "url"];
    if (slackTs) tags.push(`slack_ts:${slackTs}`);

    const noteContent = `Saved URL: ${url}\n\n${content}`;
    const memoryId = await this.bridge.remember(noteContent, tags);

    try {
      await this.bridge.triage({
        channel: "second_brain",
        payload: { action: "capture", memoryId, source: "bookmark", url, slackTs },
        priority: "low",
        tags: { second_brain_action: "capture", second_brain_source: "bookmark" },
      });
    } catch {
      // Non-fatal.
    }

    return { memoryId, source: "bookmark", slackTs };
  }

  /**
   * Fetch a Slack message by channel + ts, then store it as a bookmark note.
   *
   * Called when the user reacts with 📌 on any message.
   * Tags: ["second_brain", "bookmark", "slack_reaction"]
   */
  async bookmarkMessage(channel: string, messageTs: string): Promise<CaptureResult | null> {
    let text: string;

    try {
      const result = await this.web.conversations.replies({
        channel,
        ts: messageTs,
        limit: 1,
        inclusive: true,
      });
      const msg = result.messages?.[0];
      if (!msg?.text) return null;
      text = String(msg.text);
    } catch (err: unknown) {
      console.error("[SecondBrainHandler] Failed to fetch bookmarked message:", err);
      return null;
    }

    const tags = ["second_brain", "bookmark", "slack_reaction", `slack_ts:${messageTs}`];
    const content = `Bookmarked message (${new Date().toISOString()}):\n\n${text}`;
    const memoryId = await this.bridge.remember(content, tags);

    try {
      await this.bridge.triage({
        channel: "second_brain",
        payload: { action: "capture", memoryId, source: "bookmark", slackTs: messageTs },
        priority: "low",
        tags: { second_brain_action: "capture", second_brain_source: "bookmark" },
      });
    } catch {
      // Non-fatal.
    }

    return { memoryId, source: "bookmark", slackTs: messageTs };
  }

  // ── Query ──────────────────────────────────────────────────────────────────

  /**
   * Answer a /ask query.
   *
   * 1. Recall warm-tier notes relevant to the query.
   * 2. If the top result's score ≥ confidenceThreshold → build an inline
   *    reply from the top-k snippets (no LLM required).
   * 3. Otherwise → escalate to LLM with the retrieved context as a system
   *    prompt (budget-managed by grist-hammer).
   */
  async queryNotes(query: string): Promise<QueryResult> {
    const results = await this.bridge.recall(query, this.maxRecallLimit);

    if (results.length === 0) {
      return {
        replyText: `_GristMill:_ No notes found for *${_escapeSlack(query)}*.`,
        sourceCount: 0,
        usedLlm: false,
      };
    }

    const topScore = results[0]!.score;

    if (topScore >= this.confidenceThreshold) {
      // ── Inline reply from top results ─────────────────────────────────────
      const snippets = results
        .slice(0, 3)
        .map((r, i) => {
          const snippet = r.memory.content.slice(0, this.snippetLength).trim();
          const ellipsis = r.memory.content.length > this.snippetLength ? "…" : "";
          return `*${i + 1}.* ${snippet}${ellipsis}`;
        })
        .join("\n\n");

      return {
        replyText:
          `_GristMill:_ Found ${results.length} note(s) for *${_escapeSlack(query)}*:\n\n${snippets}`,
        sourceCount: results.length,
        usedLlm: false,
      };
    }

    // ── LLM escalation with retrieved context ─────────────────────────────
    const context = results
      .map((r, i) => `[Note ${i + 1}]: ${r.memory.content.slice(0, 600)}`)
      .join("\n\n");

    const prompt =
      `You are GristMill, a personal second brain assistant. ` +
      `Answer the user's question using ONLY the notes below. ` +
      `If the notes do not contain enough information, say so.\n\n` +
      `User question: ${query}\n\nRelevant notes:\n${context}\n\nAnswer:`;

    try {
      const escalation = await this.bridge.escalate(prompt, 512);
      return {
        replyText: `_GristMill:_ ${escalation.content.trim()}`,
        sourceCount: results.length,
        usedLlm: true,
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      // Fall back to inline reply if escalation fails.
      const fallback = results[0]!.memory.content.slice(0, this.snippetLength);
      return {
        replyText:
          `_GristMill:_ (LLM unavailable — ${msg})\n\nTop note: ${fallback}`,
        sourceCount: results.length,
        usedLlm: false,
      };
    }
  }

  // ── Thread-parent lookup ───────────────────────────────────────────────────

  /**
   * Attempt to find the memory id associated with a bot reply at `parentTs`.
   *
   * The hot sled only stores the ULID id, not the slack_ts in a queryable
   * index.  We do a best-effort recall search using the parent message text
   * and return the closest matching memory id, or null if none is found.
   *
   * This is used when the user replies in a thread to a bot message so that
   * their reply can carry a backlink to the original captured note.
   */
  async findParentMemoryId(channel: string, parentTs: string): Promise<string | null> {
    try {
      const result = await this.web.conversations.replies({
        channel,
        ts: parentTs,
        limit: 1,
        inclusive: true,
      });
      const parentText = result.messages?.[0]?.text;
      if (!parentText) return null;

      const recalls = await this.bridge.recall(String(parentText).slice(0, 200), 1);
      return recalls[0]?.memory.id ?? null;
    } catch {
      return null;
    }
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Fetch a URL and return its text content (HTML stripped to plain text).
 * Times out after 10 s.  Throws on non-2xx or unsupported content type.
 */
async function _fetchUrl(url: string): Promise<string> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 10_000);

  let response: Response;
  try {
    response = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": "GristMill-SecondBrain/1.0" },
    });
  } finally {
    clearTimeout(timeoutId);
  }

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }

  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("text/html") && !contentType.includes("text/plain")) {
    throw new Error(`Unsupported content type: ${contentType}`);
  }

  const html = await response.text();
  return _stripHtml(html).slice(0, 8_000);
}

/** Strip HTML tags and decode common entities, then collapse whitespace. */
function _stripHtml(html: string): string {
  let text = html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<nav[\s\S]*?<\/nav>/gi, " ")
    .replace(/<footer[\s\S]*?<\/footer>/gi, " ")
    .replace(/<header[\s\S]*?<\/header>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&nbsp;/gi, " ");
  return text.replace(/\s+/g, " ").trim();
}

/** Escape Slack mrkdwn special characters in user-provided strings. */
function _escapeSlack(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
