"""
Pydantic v2 schema for SecondBrainNote.

A SecondBrainNote is the Python representation of a note stored in the warm
tier by the TypeScript SecondBrainHandler.  It extends the base Memory
schema with second-brain specific fields (summary, backlinks, slack metadata).

This schema is used by:
  - SecondBrainProcessor  — enriches raw captures with summaries and backlinks
  - MLflow experiment tracking — logs note-level metrics during processing runs
  - Any downstream tooling that reads notes from the warm SQLite tier

Fields are intentionally a superset of grist-ledger's Memory struct so that a
warm-tier row can be hydrated into a SecondBrainNote without data loss.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class SecondBrainNote(BaseModel):
    """A note in the second brain corpus."""

    # ── Identity ──────────────────────────────────────────────────────────────

    id: str = Field(
        description="ULID assigned by grist-ledger when the note was captured."
    )

    # ── Content ───────────────────────────────────────────────────────────────

    content: str = Field(
        description="Raw text content as stored in the ledger."
    )
    summary: str = Field(
        default="",
        description=(
            "One-paragraph summary generated by the local LLM (Ollama). "
            "Empty until the processor has run against this note."
        ),
    )
    tags: list[str] = Field(
        default_factory=list,
        description=(
            "Tags from grist-ledger (e.g. 'second_brain', 'capture', "
            "'bookmark') plus processor-added domain tags."
        ),
    )

    # ── Provenance ────────────────────────────────────────────────────────────

    source: Literal[
        "slack_dm",
        "slack_forward",
        "slack_reaction",
        "url",
        "thread_reply",
        "unknown",
    ] = Field(
        default="unknown",
        description=(
            "How the note was captured. Derived from the 'second_brain_source' "
            "tag set by the TypeScript SecondBrainHandler."
        ),
    )
    slack_ts: str | None = Field(
        default=None,
        description=(
            "Original Slack message timestamp (e.g. '1713200000.000100'). "
            "Used to construct deep-links back to the source message. "
            "Extracted from the 'slack_ts:<value>' tag."
        ),
    )

    # ── Embedding ─────────────────────────────────────────────────────────────

    embedding: list[float] = Field(
        default_factory=list,
        description=(
            "Dense embedding vector from the local embedding model "
            "(e.g. nomic-embed-text via Ollama, or MiniLM from the warm tier). "
            "Empty until the processor has computed it."
        ),
    )

    # ── Knowledge graph ───────────────────────────────────────────────────────

    backlinks: list[str] = Field(
        default_factory=list,
        description=(
            "IDs of other notes that this note references or that reference "
            "this note, as determined by vector similarity and explicit "
            "[backlink:<id>] markers left by the SlackHopper."
        ),
    )

    # ── Timestamps ────────────────────────────────────────────────────────────

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="Wall-clock time when the note was first captured.",
    )
    last_accessed: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="Wall-clock time when the note was last retrieved via recall().",
    )

    # ── Storage tier ──────────────────────────────────────────────────────────

    tier: Literal["hot", "warm", "cold"] = Field(
        default="warm",
        description="Current storage tier in grist-ledger.",
    )

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("id")
    @classmethod
    def id_must_be_nonempty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("id must be a non-empty ULID string")
        return v

    @field_validator("content")
    @classmethod
    def content_must_be_nonempty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("content must be non-empty")
        return v

    # ── Convenience helpers ───────────────────────────────────────────────────

    @classmethod
    def from_ledger_tags(cls, id: str, content: str, tags: list[str], **kwargs) -> "SecondBrainNote":
        """
        Hydrate a SecondBrainNote from a grist-ledger Memory's id, content, and
        tag list.

        Tag conventions (set by the TypeScript SecondBrainHandler):
          'slack_ts:<value>'         → note.slack_ts
          'second_brain_source:<v>'  → note.source   (fallback: guess from tags)
          'bookmark'                 → source='url' or 'slack_reaction'
          'capture'                  → source='slack_dm'
          'linked'                   → source='thread_reply'
        """
        slack_ts: str | None = None
        source: str = "unknown"

        for tag in tags:
            if tag.startswith("slack_ts:"):
                slack_ts = tag[len("slack_ts:"):]
            elif tag.startswith("second_brain_source:"):
                source = tag[len("second_brain_source:"):]

        # Fallback: infer source from coarser tags
        if source == "unknown":
            if "url" in tags:
                source = "url"
            elif "slack_reaction" in tags:
                source = "slack_reaction"
            elif "linked" in tags:
                source = "thread_reply"
            elif "capture" in tags:
                source = "slack_dm"

        return cls(
            id=id,
            content=content,
            tags=tags,
            slack_ts=slack_ts,
            source=source,  # type: ignore[arg-type]
            **kwargs,
        )

    def is_enriched(self) -> bool:
        """Return True if the note has already been processed (has a summary)."""
        return bool(self.summary.strip())

    def has_embedding(self) -> bool:
        """Return True if a non-zero embedding vector has been computed."""
        return bool(self.embedding) and any(v != 0.0 for v in self.embedding)

    def days_since_accessed(self) -> float:
        """Return fractional days since last_accessed (UTC)."""
        now = datetime.now(tz=timezone.utc)
        delta = now - self.last_accessed.replace(tzinfo=timezone.utc)
        return delta.total_seconds() / 86_400
